CREATE DATABASE social_network DEFAULT CHARACTER SET utf8 COLLATE utf8_unicode_ci;
use social_network;


CREATE TABLE IF NOT EXISTS users (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  userName VARCHAR(150) NOT NULL,
  password VARCHAR(150) NOT NULL,
  fullName VARCHAR(127) NOT NULL,
  email VARCHAR(255) NOT NULL,
  role VARCHAR(20) NOT NULL
);

CREATE TABLE IF NOT EXISTS userinfos (
  id INT UNIQUE,
  studyAt VARCHAR(255) NOT NULL,
  workingAt VARCHAR(255) NOT NULL,
  otherInfo VARCHAR(1023) NOT NULL,
  dateOfBirth VARCHAR(100) NOT NULL,
  avatarUrl VARCHAR(255) NOT NULL,
  FOREIGN KEY (id) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS posts (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  content VARCHAR(3000) NOT NULL,
  contentUrl VARCHAR(255) NOT NULL,
  likeCount INT NOT NULL,
  shareCount INT NOT NULL,
  commentCount INT NOT NULL,
  category VARCHAR(150) NOT NULL,
  FOREIGN KEY (userId) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS notifications (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  postId INT NOT NULL,
  userId INT NOT NULL,
  content VARCHAR(255) NOT NULL,
  FOREIGN KEY (userId) REFERENCES users (id),
  FOREIGN KEY (postId) REFERENCES posts (id)
);

CREATE TABLE IF NOT EXISTS comments (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  postId INT NOT NULL,
  userId INT NOT NULL,
  content VARCHAR(255) NOT NULL,
  FOREIGN KEY (userId) REFERENCES users (id),
  FOREIGN KEY (postId) REFERENCES posts (id)
);
CREATE TABLE IF NOT EXISTS films (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  userId INT NOT NULL,
  title VARCHAR(255) NOT NULL,
  contentUrl VARCHAR(255) NOT NULL,
  content VARCHAR(255) NOT NULL,
  FOREIGN KEY (userId) REFERENCES users (id)
);

CREATE TABLE IF NOT EXISTS groupchats (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  userAdmin INT NOT NULL,
  user1 VARCHAR(150) NOT NULL,
  user2 VARCHAR(150) NOT NULL,
  user3 VARCHAR(150) NOT NULL,
  user4 VARCHAR(150) NOT NULL,
  user5 VARCHAR(150) NOT NULL,
  FOREIGN KEY (userAdmin) REFERENCES users (id)
);
CREATE TABLE IF NOT EXISTS messages (
  id INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
  groupChatId INT NOT NULL,
  userId INT NOT NULL,
  content VARCHAR(255) NOT NULL,
  FOREIGN KEY (userId) REFERENCES users (id),
  FOREIGN KEY (groupChatId) REFERENCES posts (id)
);
